### ISSUE TITLE
dns query flood

### ISSUE THREAD

**Issue by MaestroPajero** [All3xJ/Hibernet#1]
Would be possible to add this feature ? Thank you

**Comment by All3xJ** [comment]
You mean DNS amplification attack?

**Comment by MaestroPajero** [comment]
Hello I dont speak very well english so I will let you 2 web where you can read it , This is used by mirai and works like,  asdf.domain.com , where asdf is random data. 

https://community.infoblox.com/t5/Security-Blog/DNS-Based-DDoS-Attacks-What-s-In-a-Name/ba-p/8465
http://www.zdnet.com/article/mirai-dns-water-torture-finance-sector-attack-dominated-q1-akamai/

There was a good article about this but I cant found it right know, whatever thank you for reply

**Comment by All3xJ** [comment]
I'll see what I can do to implement a DNS amplification attack... But only when I'll be in Christmas holidays I guess...

**Comment by MaestroPajero** [comment]
I think is not a DNS amplification atack , the name of the atack is DNS water torture but anways, lot of thanks

**Comment by Beyarz** [comment]
I think what you're referring to is a so called "NXDOMAIN Attack".
