### ISSUE TITLE
Bypass Cloudflare "I'm under attack"

### ISSUE THREAD

**Issue by Marko97IT** [All3xJ/Hibernet#11]
Ciao amico,
Ti scrivo in italiano perché tanto mi capisci.
Il tuo software è un qualcosa di sensazionale!!! Di una potenza unica. Unica pecca che se attivano il blocco di Cloudflare non si può più fare nulla.
Riesci ad implementare questo modulo python?
Ti lascio il link e fammi sapere :)

LINK: https://github.com/Anorov/cloudflare-scrape

**Comment by trollmad3** [comment]
This issue is translated with google translate:
Hello Friend,
I write you in Italian because you understand me so much.
Your software is something sensational !!! Of a unique power. The only flaw that if you activate the blockade of Cloudflare can not do anything.
Can you implement this python module?
I leave you the link and let me know :)

**Comment by All3xJ** [comment]
> Ciao amico,
> Ti scrivo in italiano perché tanto mi capisci.
> Il tuo software è un qualcosa di sensazionale!!! Di una potenza unica. Unica pecca che se attivano il blocco di Cloudflare non si può più fare nulla.
> Riesci ad implementare questo modulo python?
> Ti lascio il link e fammi sapere :)
> 
> LINK: https://github.com/Anorov/cloudflare-scrape

I answer you in english so everyone can understand. What you mean for: "if _they_ activate cloudflare block the attack can not be done"? This program is built to test the security of your own server, not _someone else_ 's server. And also, who does prevent you from integrate that cloudflare bypass module in this program? If you do it, you can let us now, it's the beauty of open source.

**Comment by Aholicknight** [comment]
@Marko97IT 

Translated for you:

Te contesto en inglés para que todo el mundo lo entienda. ¿Para qué quieres decir: "si activan el bloqueo de cloudflare el ataque no se puede hacer"? Este programa está diseñado para probar la seguridad de su propio servidor, no del servidor de otra persona. Y también, ¿quién le impide integrar ese módulo de bypass cloudflare en este programa? Si lo haces, puedes hacérnoslo saber, es la belleza del código abierto.

**Comment by BitRevenant** [comment]
> @Marko97IT 
> 
> Translated for you:
> 
> Te contesto en inglés para que todo el mundo lo entienda. ¿Para qué quieres decir: "si activan el bloqueo de cloudflare el ataque no se puede hacer"? Este programa está diseñado para probar la seguridad de su propio servidor, no del servidor de otra persona. Y también, ¿quién le impide integrar ese módulo de bypass cloudflare en este programa? Si lo haces, puedes hacérnoslo saber, es la belleza del código abierto.

I'm not Spanish but Italian, also I can understand english. Anyway thank you. :)

**Comment by Aholicknight** [comment]
Alright.
