### ISSUE TITLE
This guy is stealing and claiming it

### ISSUE THREAD

**Issue by MaestroPajero** [All3xJ/Hibernet#16]
This clown: https://github.com/UN5T48L3/UnstableDDoS

**Comment by aa21** [comment]
Calm down. This is how Open Source works.

**Comment by MaestroPajero** [comment]
The thing is , he is claiming that he did it by adding "# C0d3d by UN5T48L3",  idc if he uses and modify the code (but im sure he cant even add a print line lol)

**Comment by All3xJ** [comment]
> Calm down. This is how Open Source works.

Open Source is not claiming you have done something done by another person without editing anything.



> This clown: https://github.com/UN5T48L3/UnstableDDoS

Thanks for reporting, it seems he deleted it anyway.
