### ISSUE TITLE
Need to execute the program in one command line & add HTTPS support

### ISSUE THREAD

**Issue by ghost** [All3xJ/Hibernet#17]
Hi,
To control several servers launch attack at the same time, it will be easier if you could make this program executable in one single command, for example, "python3 HibernetV2.1 --target http://google.com --mode HTTP --threads 1000 --process 200"

Also, Hibernet currently can't perform the attack on HTTPS used websites, please find a solution to solve the issue.

I can personally pay you 100$ to work on this.

**Comment by skizap** [comment]
why Don't you work on it yourself?

**Comment by All3xJ** [comment]
> Hi,
> To control several servers launch attack at the same time, it will be easier if you could make this program executable in one single command, for example, "python3 HibernetV2.1 --target http://google.com --mode HTTP --threads 1000 --process 200"
> 
> Also, Hibernet currently can't perform the attack on HTTPS used websites, please find a solution to solve the issue.
> 
> I can personally pay you 100$ to work on this.

are you still interested and available for payment?
