### ISSUE TITLE
Udp Or Tcp DDos Not WORKING

### ISSUE THREAD

**Issue by Gladiator666Satan** [All3xJ/Hibernet#20]
when choosing a flood method: http, tcp, udp
http - working
tcp and udp - shuts down with a critical error

**Comment by ceekfade** [comment]
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "HibernetV2.2.py", line 760, in run
    p = bytes(IP(dst=str(url2))/TCP(sport=RandShort(), dport=int(port))/data) # costruzione pacchetto tcp + data
NameError: name 'IP' is not defined

**Comment by ceekfade** [comment]
Can you please fix this error?

**Comment by Theprim0** [comment]
Same here, same error with TCP or UDP

**Comment by SimplePlay** [comment]
I have the same error(

**Comment by All3xJ** [comment]
the only supported is http.
tcp and udp have been removed since they were not anonymized.
